### ISSUE TITLE
Flutter app fails to run on Android and iOS due to UnmodifiableUint8ListView error and CocoaPods issue with RunnerTests target.

### ISSUE THREAD

**Issue by Turskyi** [gaaclarke/romeo_juliet#1]
While reading the documentation on [Flutter Isolates](https://docs.flutter.dev/perf/isolates#more-information) and reviewing the example on [isolate_agents](https://pub.dev/packages/isolate_agents/example), I eventually landed on the [romeo_juliet](https://github.com/gaaclarke/romeo_juliet) repository, as it appeared to be the only available source demonstrating how this package should work. However, I encountered issues when trying to run the example app, and it does not function as expected.

1. **Android Emulator**: The app fails to build with the following error:
```
../../../../.pub-cache/hosted/pub.dev/win32-3.1.2/lib/src/guid.dart:31:9: Error: Type 'UnmodifiableUint8ListView' not found.
  final UnmodifiableUint8ListView bytes;
        ^^^^^^^^^^^^^^^^^^^^^^^^^
```

- Android Emulator details:

  - API: 30 (Android version 11)
  - Device: Medium Phone
  - Google Play Store enabled

2. **iOS Simulator**: The app fails with a CocoaPods error, preventing the app from launching:
```
[!] Unable to find a target named `RunnerTests` in project `Runner.xcodeproj`, did find `Runner`.
```
Additionally, there's an automatic platform assignment warning:
```
Automatically assigning platform `iOS` with version `12.0` on target `Runner` because no platform was specified.
```

- iOS Simulator details:

  - Device: iPhone 16 Plus
  - Platform: iOS 12
  - Steps to reproduce:

1. Clone the repository: https://github.com/gaaclarke/romeo_juliet
2. Follow the "Getting started" guide.
3. Run flutter run on Android and iOS platforms.

**Environment**:

Flutter version: 3.24.3
Dart version: 3.5.3
Android Emulator API: 30
iOS Simulator: iPhone 16 Plus
MacBook Pro with macOS (Apple Silicon M1)

Could you please advise on how to resolve these issues? Should any configuration changes be made to the project to address the UnmodifiableUint8ListView error on Android and the CocoaPods issue with the missing RunnerTests target on iOS?

**Comment by gaaclarke** [comment]
Thanks for the report, I've fixed it.  This was just because of bit rot.  The fixes were:
1) Remove the platform files from the repo so they can't get out of date.  People can generate them with `flutter create .`
1) Update `path_provider`.  This is unfortunate that such fundamental functionality can rot.
